function toLegacyWebsiteFindings(manifest, options = {}) {
  const s = manifest.summary || {};
  const scoring = manifest.scoring || {};
  const booking = manifest.bookingFlow || {};
  return {
    reviewedUrl: manifest.reviewedUrl,
    screenshotUrl: options.screenshotUrl || '',
    screenshotPath: manifest.desktop?.screenshots?.hero || '',
    phoneVisible: !!s.phoneVisible,
    bookingCtaVisible: !!s.bookingCtaVisible,
    messengerWhatsappVisible: !!s.messengerWhatsappVisible,
    lineVisible: !!s.lineVisible,
    whatsappVisible: !!s.whatsappVisible,
    whatsappPatientContactVisible: !!s.whatsappPatientContactVisible,
    socialPresence: s.socialPresence || {},
    messengerVisible: !!s.messengerVisible,
    trustSignalsVisible: !!s.trustSignalsVisible,
    onlineBookingVisible: !!s.onlineBookingVisible,
    googleMapsVisible: !!s.googleMapsVisible,
    reviewsVisible: !!s.reviewsVisible,
    doctorProfileVisible: !!s.doctorProfileVisible,
    clinicianMentionVisible: !!s.clinicianMentionVisible,
    beforeAfterVisible: !!s.beforeAfterVisible,
    pricingVisible: !!s.pricingVisible,
    primaryDesktopCta: s.primaryDesktopCta || null,
    primaryMobileCta: s.primaryMobileCta || null,
    heroMediaType: s.heroMediaType || 'none',
    mobileHeroCrowding: s.mobileHeroCrowding || 0,
    mobileHeroClarity: s.mobileHeroClarity || 0,
    desktopAttentionFragmentation: s.desktopAttentionFragmentation || 0,
    mobileAttentionFragmentation: s.mobileAttentionFragmentation || 0,
    firstVisitCookieConsentDetected: !!s.firstVisitCookieConsentDetected,
    firstVisitCookieCoverageMobilePercent: s.firstVisitCookieCoverageMobilePercent || 0,
    bookingFlowAnalyzed: !!booking.analyzed,
    bookingExternalProvider: !!booking.externalProvider,
    bookingFieldCount: booking.fieldCount || 0,
    bookingRequiredFieldCount: booking.requiredFieldCount || 0,
    bookingLoginRequired: !!booking.loginRequired,
    bookingFrictionScore: booking.frictionScore ?? null,
    bookingStepCount: booking.detectedStepCount || booking.inferredStepCount || 1,
    bookingTraversedStepCount: booking.traversedStepCount || 0,
    bookingTotalFieldCount: booking.totalFieldCount || booking.fieldCount || 0,
    bookingTotalRequiredFieldCount: booking.totalRequiredFieldCount || booking.requiredFieldCount || 0,
    bookingJourneyScore: booking.bookingJourneyScore ?? null,
    bookingSubScores: booking.subScores || null,
    bookingManualConfirmation: !!booking.manualConfirmationDetected,
    bookingMinimumAdvanceDays: booking.minimumAdvanceDays ?? null,
    bookingResponseWithinDays: booking.responseWithinDays ?? null,
    deterministicScore: scoring.overall ?? null,
    deterministicCategories: scoring.categories || null,
    explainability: scoring.explainability || null,
    siteDiscovery: manifest.siteDiscovery ? { discoveredCount: manifest.siteDiscovery.discoveredCount, selectedDeepPages: manifest.siteDiscovery.selectedDeepPages } : null,
    pageJourney: manifest.pageJourney ? { selectedCount: manifest.pageJourney.selectedCount, pages: (manifest.pageJourney.pages || []).map(p=>({url:p.url,pageType:p.pageType,commercialScore:p.commercialScore})) } : null,
    flags: scoring.flags || [],
    automatedFindings: manifest.findings?.findings || []
  };
}
module.exports = { toLegacyWebsiteFindings };
