const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const src=fs.readFileSync(__dirname+'/facebook-probe.js','utf8');
const start=src.indexOf('function countExplicitReplyLabels');
const end=src.indexOf('\nasync function collectPublicCommentEvidence',start);
const fnSrc=src.slice(start,end)+'\nmodule.exports={countExplicitReplyLabels,commentEvidenceScore,mergeCommentEvidence};';
const sandbox={module:{exports:{}},exports:{},require,console};
vm.runInNewContext(fnSrc,sandbox);
const {countExplicitReplyLabels,commentEvidenceScore,mergeCommentEvidence}=sandbox.module.exports;
const body='Reneboy Location 34w Like Reply 2 Yu Dental Davao replied · 1 reply Tina Up lng how much? 25w Like Reply 5 Yu Dental Davao replied · 2 replies';
assert.equal(countExplicitReplyLabels(body,'(8) Facebook','yudentalcenterdavao'),2);
const weak=[{sourceUrl:'u',author:'Tina',text:'how much',clinicReplyObserved:false,replyAssociationMode:null}];
const rich=[{sourceUrl:'u',author:'Tina',text:'how much',clinicReplyObserved:true,clinicReplyIndicatorLabel:'Yu Dental Davao replied · 2 replies',clinicReplyCount:2,replyAssociationMode:'raw-rendered-text'}];
const merged=mergeCommentEvidence([weak,rich]);
assert.equal(merged.length,1);
assert.equal(merged[0].clinicReplyObserved,true);
assert.equal(merged[0].clinicReplyCount,2);
assert(commentEvidenceScore(rich,{bodyText:body,pageName:'(8) Facebook',handle:'yudentalcenterdavao',articles:[1]})>commentEvidenceScore(weak,{bodyText:'',articles:[1]}));
console.log('facebook-probe-v2115 ok');
