const assert=require('assert');
const {scoreFacebook}=require('./facebook');
const comments=[];
for(let i=0;i<12;i++)comments.push({patientIntent:true,pricingIntent:true,clinicReplyObserved:true,timestampLabel:'8w'});
for(let i=0;i<2;i++)comments.push({patientIntent:true,pricingIntent:true,clinicReplyObserved:false,timestampLabel:'8w'});
for(let i=0;i<7;i++)comments.push({patientIntent:true,generalInterestIntent:true,clinicReplyObserved:false,timestampLabel:'8w'});
const evidence={status:'probed',destination:{httpReachable:true,landsOnClinicPage:true,genericFacebookDestination:false,wrongPage:false},actions:{bookButtonPresent:true,bookButtonWorks:true,bookingRequiresLogin:false,messageButtonPresent:true},consistency:{brandNameMatches:true,bookingLinkQuality:100},demand:{comments},probe:{probeDiagnostics:{commentPostDiscovery:{postsFound:12,postsInspected:5,evidenceAccumulation:{renderAttempts:13,statesRetained:5,variablePosts:3}}}},provenance:{collectedAt:new Date().toISOString()},revenueModel:{delayThresholdMinutes:60}};
const s=scoreFacebook(evidence);
assert.equal(s.responseMetrics.observedIntentComments,21);
assert.equal(s.responseMetrics.answeredIntentCount,12);
assert.equal(s.responseMetrics.responseCoveragePercent,57);
assert.equal(s.responseMetrics.scoringObservedIntentComments,14);
assert.equal(s.responseMetrics.scoringAnsweredIntentCount,12);
assert.equal(s.responseMetrics.scoringUnansweredIntentCount,2);
assert.equal(s.responseMetrics.scoringResponseCoveragePercent,86);
assert.equal(s.responseMetrics.generalInterestObservedCount,7);
assert.equal(s.responseMetrics.generalInterestUnansweredCount,7);
assert.equal(s.responseMetrics.generalInterestResponseCoveragePercent,0);
assert.equal(s.demandLeakage.unansweredHighIntentLeads,2);
assert.equal(s.demandLeakage.generalInterestLeadsUnanswered,7);
assert.equal(s.components.responsePerformance,86);
console.log('facebook-probe-v2119.test.js passed');
