const assert=require('assert');
const fs=require('fs'); const os=require('os'); const path=require('path');
const {selectedAuditScreenshots,responseSchema,runAuditIntelligence}=require('./openai-audit-intelligence');
const {applyFacebookVisualSurfaceEvidence,scoreFacebook}=require('./facebook');
(async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'eden-v2217-')); const png=Buffer.from('89504e470d0a1a0a','hex');
 const shot=n=>{const p=path.join(dir,n);fs.writeFileSync(p,png);return p};
 const manifest={version:'2.2.17',findings:{findings:[]},summary:{},scoring:{categories:{}},facebook:{assessment:{status:'insufficient-evidence'}},facebookProbe:{status:'probed',authentication:{used:true,status:'authenticated-session'},screenshots:{desktop:shot('fb-auth-desktop.png'),mobile:shot('fb-auth-mobile.png')},destination:{landsOnClinicPage:true,wrongPage:false,genericFacebookDestination:false},page:{pageName:'Pattaya Smile Dental Clinic',followerCount:null,recommendationPercent:null,recommendationReviewCount:null,phone:null,address:null},actions:{messageButtonStatus:'observed',messageButtonPresent:true},consistency:{brandNameMatches:true}}};
 const labels=selectedAuditScreenshots(manifest).map(x=>x.label); assert(labels.includes('facebook-authenticated-desktop')); assert(!labels.includes('facebook-public-desktop'));
 const schema=responseSchema(); assert(schema.required.includes('facebookSurfaceEvidence'));
 let requested; const na={assessment:'not_assessable',confidence:'low',rationale:'x',evidenceScreenshots:[]};
 const fake={validation:[],conflicts:[],visualAssessments:{heroClarity:na,primaryActionQuality:na,mobileVisualQuality:na,trustPresentation:na,perceivedFriction:na},googleBusinessVisualAssessments:{profileIdentity:na,reputationPresentation:na,actionAccess:na,bookingPath:na,visualTrust:na},facebookVisualAssessments:{profileIdentity:{assessment:'strong',confidence:'high',rationale:'clinic page visible',evidenceScreenshots:['facebook-authenticated-desktop']},actionAccess:{assessment:'strong',confidence:'high',rationale:'Message visible',evidenceScreenshots:['facebook-authenticated-desktop']},demandVisibility:na,responseEvidence:na,handoffQuality:{assessment:'adequate',confidence:'high',rationale:'Message action visible',evidenceScreenshots:['facebook-authenticated-desktop']},receptionistOpportunity:{opportunity:'not_assessable',confidence:'low',rationale:'no demand evidence',evidenceScreenshots:[]}},facebookSurfaceEvidence:{observationMode:'authenticated',pageName:'Pattaya Smile Dental Clinic',followerCount:4300,recommendationPercent:98,recommendationReviewCount:297,phone:'086 334 2004',address:'111/57-58 Nong Prue, Bang Lamung, Chon Buri',messageActionVisible:true,callActionVisible:null,bookingActionVisible:null,latestVisibleActivityLabel:'Aug 28',recentVisiblePostLabels:['Aug 28','Aug 26'],visiblePostCount:2,engagementSamples:[{label:'Aug 28 visible post',reactionCount:1,commentCount:0,shareCount:null}],contentPresentation:{assessment:'cluttered',rationale:'Promotional graphics contain dense text.'},confidence:'high',evidenceScreenshots:['facebook-authenticated-desktop']},narrative:{executiveSummary:'x',costingPatients:'x',topPriorities:[{title:'x',why:'x',evidenceBasis:'x'}],quickWins:[{title:'x',action:'x',evidenceBasis:'x'}],pillarExplanations:{website:'x',googleBusiness:'x',facebook:'x'},caveats:[],edenIntervention:'x'}};
 const fetchImpl=async(_u,o)=>{requested=JSON.parse(o.body);return {ok:true,json:async()=>({id:'r',model:'gpt-5.6-terra',output_text:JSON.stringify(fake)})}};
 const ai=await runAuditIntelligence(manifest,{}, {force:true,apiKey:'x',fetchImpl}); assert.equal(ai.facebookSurfaceEvidence.followerCount,4300);
 const input=requested.input[0].content[0].text; assert(/provenance is binding/i.test(input)); assert(/authenticated surface extraction/i.test(input));
 const base={status:'evidence-collected',destination:{httpReachable:true,landsOnClinicPage:true,genericFacebookDestination:false,wrongPage:false},page:{pageName:'Pattaya Smile Dental Clinic',followerCount:null,recommendationPercent:null,recommendationReviewCount:null,phone:null,address:null},actions:{messageButtonPresent:true,bookButtonPresent:null,callButtonPresent:null,whatsappButtonPresent:null},consistency:{brandNameMatches:true},demand:{comments:[]},response:{},provenance:{}};
 const merged=applyFacebookVisualSurfaceEvidence(base,ai); assert(merged.applied); assert.equal(merged.evidence.page.followerCount,4300); assert.equal(merged.evidence.page.recommendationReviewCount,297); assert.equal(merged.evidence.page.phone,'086 334 2004');
 const scored=scoreFacebook(merged.evidence); assert(scored.overall!==null); console.log('robustness-v2217 tests passed');
})().catch(e=>{console.error(e);process.exit(1)});
